# Generated by Django 5.0.2 on 2025-05-30 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='people',
            field=models.ManyToManyField(related_name='media_items', to='family.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='family.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_events', to='family.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_person1', to='family.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_person2', to='family.person'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('person1', 'person2', 'relationship_type')},
        ),
    ]
