# Generated by Django 5.2.8 on 2026-09-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("family", "0003_alter_relationship_options_familytree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="clan_totem",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Clan Totem / Symbole"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="generation_tier",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Generation Tier"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="traditional_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Traditional Name / Nom Coutumier",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="village_of_origin",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Village of Origin / Chefferie"
            ),
        ),
    ]
