# Generated by Django 5.2.17 on 2026-10-05 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("family", "0007_person_search_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("PRIVACY", "Privacy"),
                            ("INCORRECT", "Incorrect information"),
                            ("INAPPROPRIATE", "Inappropriate content"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("details", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Received"),
                            ("IN_REVIEW", "Under review"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("response", models.TextField(blank=True, max_length=2000)),
                ("request_key", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="family.person",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="family.familytree",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reporter", "request_key"), name="unique_report_request"
                    )
                ],
            },
        ),
    ]
