# Generated by Django 5.2.8 on 2026-09-19 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_options_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeritageKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Sacred Heritage Passkey string, e.g. KKEVO-ROYAL-7A89-B42F",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Sacred Heritage Key", max_length=100),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ROYAL_PATRIARCH", "Royal Patriarch / Elder"),
                            ("CURATOR", "Dynasty Curator"),
                            ("FAMILY_MEMBER", "Lineage Member"),
                            ("GUEST_VIEWER", "Guest Lineage Viewer"),
                        ],
                        default="FAMILY_MEMBER",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User associated with this Heritage Key",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heritage_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Heritage Key",
                "verbose_name_plural": "Heritage Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
