# Generated by Django 5.2.8 on 2026-09-20 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("family", "0004_person_clan_totem_person_generation_tier_and_more"),
        ("users", "0003_heritagekey"),
    ]

    operations = [
        migrations.AddField(
            model_name="heritagekey",
            name="family_tree",
            field=models.ForeignKey(
                blank=True,
                help_text="Family tree this key grants access to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="heritage_keys",
                to="family.familytree",
            ),
        ),
        migrations.AddField(
            model_name="heritagekey",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="Person in the family tree this key is bound to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="heritage_keys",
                to="family.person",
            ),
        ),
    ]
